<?php

/**
 * Implements hook_menu().
 */
function funding_menu() {
  $items = array();

  $items['admin/funding'] = array(
    'title' => 'Funding',
    'description' => 'Administer Funding.',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file path' => drupal_get_path('module', 'system'),
    'file' => 'system.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}
